### ISSUE TITLE
esg-orp.war missing in esgf-data-node dockerfile

### ISSUE THREAD

**Issue by gurvindersingh** [LucaCinquini/docker#1]
Thanks Luca for your work on making docker repo for esgf data node. I am trying to test it on my laptop for now and when I try to build the image, i get this error

esgf-orp/esg-orp.war: no such file or directory

as the file in not present in the repo. Can you tell me how to fix it and in general what's the plan with having a working official docker images for esgf components. I am trying to see if I can run this on kubernetes.

**Comment by gurvindersingh** [comment]
it seems the war file are suppose to be downloaded from url and placed in this directory. E.g. esg-orp.war: wget http://rainbow.llnl.gov/dist/esg-orp/esg-orp.war

But the tomcat-users.xml and /esg/config/tomcat/keystore-tomcat files are also missing. I saw that in your docker-compose file you are mounting this volume any plan to have guidelines as how/what should be there or have same default examples already baked into the image.

**Comment by LucaCinquini** [comment]
Hi Gurvinder,
actually I had no idea you were testing these images... I would strongly recommend to wait at least a few weeks because this infrastructure is very much under development and changing continuously. I actually started working on this again just today and intend to have something to demo at the next ESGF conference call (around late October). But before that, I think you don't want to waste your time. Sorry about that - I will let you know when things are stable.

**Comment by gurvindersingh** [comment]
Thanks Luca for the reply. Good to know that you will be working on making it work now. Let me know if you need any help in testing or development, as I also plan to have demo of it around late October (27th), so hopefully it is working by then :)

**Comment by gurvindersingh** [comment]
it has been resolved
